config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'

    resources :addresses
    resources :items
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items
    patch '/cart_items' => 'cart_items#update'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    resources :orders
  end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'homes#top'
    resources :items

    resources :genres

    resources :customers

    resources :orders
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
  
  validates :name, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end

  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, presence: true
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  # アソシエーションの設定
  belongs_to :genre

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  ## 消費税を求めるメソッド
  def with_tax_price
    (price_without_tax * 1.1).floor
  end

  validates :name, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  belongs_to :customer
  has_many :order_details
  has_many :items ,through: :order_details
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  def subtotal
    price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save!
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save!
      redirect_to admin_item_path(@item)
    else
      render :index
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :genre_id, :name, :introduction, :price_without_tax, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @oders = Order.all
  end
  
  def show
    @order = Order.find(params[:id])
    @order.shipping_cost = 800
  end
  
  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path
    when Customer
      root_path
    end
  end

#サインアップ後の遷移先を指定する方法

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
        new_admin_session_path
    else resource_or_scope == :customer
        root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_details_helper.rb
module Admin::OrdersDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <h2>ジャンル編集</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <table class="table">
      　<%= form_with model: @genre,url: admin_genre_path, method: :patch do |f| %>
        <tbody>
          <tr>
            <th>ジャンル名</th>
            <td><%= f.text_field :name %></td>
            <td><%= f.submit '変更を保存', class:"btn btn-success" %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <h2>ジャンル一覧・追加</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-5">
      <table class="table">
        <%= form_with model: @genre,url: admin_genres_path do |f| %>
        <tbody>
          <tr>
            <th>ジャンル名</th>
            <td><%= f.text_field :name %></td>
            <td><%= f.submit '新規登録', class:"btn btn-success" %></td>
          </tr>
        </tbody>
        <% end %>
      </table>

      <table class="table table-striped">
      <% @genres.each do |genre| %>
        <tbody>
          <tr>
            <th><%= genre.name %></th>
            <td><%= link_to "編集する", edit_admin_genre_path(genre), class:"btn btn-success" %></td>
          </tr>
        </tbody>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <h2>編集画面</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="mx-auto">
    <table class="table table-borderless">
      <tbody>
        <%= form_with model: @item,url: admin_item_path do |f| %>
        <tr>
          <th>商品画像</th>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr>
          <th>商品名</th>
          <td><%= f.text_field :name, class: "form-control" %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= f.text_area :introduction, class: "form-control" %></td>
        </tr>
        <tr>
          <th>税抜価格</th>
          <td><%= f.text_field :price_without_tax %>円</td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= f.collection_select(:genre_id, Genre.all, :id, :name) %></td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
             <%= f.radio_button :is_active, true %>
             <%= f.label :is_active, "販売中" %>
             <%= f.radio_button :is_active, false %>
             <%= f.label :is_active, "販売停止中" %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td><%= f.submit '変更を保存', class:"btn btn-success" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <h3>商品一覧</h3>
    </div>
    <div class="text-right">
      <%= link_to "新規登録",new_admin_item_url %>
    </div>
  </div>


  <div class="row">
    <div class="col-md-10 mx-auto">
      <table class="table">
        <thead>
          <tr>
            <th>商品id</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, "items/#{item.id}" %></td>
            <td><%= item.price_without_tax %>円</td>
            <td><%= item.genre.name %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
  <div class="row mt-5">
    <div class="mx-auto">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <h2>商品新規登録</h2>
    </div>
  </div>

<div class="row">
  <div class="mx-auto">
    <%= form_with model: @item,url: admin_items_path, method: :post do |f| %>
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th>商品画像</th>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr>
          <th>商品名</th>
          <td><%= f.text_field :name, class: "form-control" %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= f.text_area :introduction, class: "form-control" %></td>
        </tr>
        <tr>
          <th>税抜価格</th>
          <td><%= f.text_field :price_without_tax %>円</td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= f.collection_select(:genre_id, Genre.all, :id, :name) %></td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
             <%= f.radio_button :is_active, true %>
             <%= f.label :is_active, "販売中" %>
             <%= f.radio_button :is_active, false %>
             <%= f.label :is_active, "販売停止中" %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td><%= f.submit '新規登録', class:"btn btn-success" %></td>
        </tr>
      </tbody>
    </table>
    <% end %>
  </div>
</div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <h2>商品詳細</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="mx-auto">
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th></th>
          <td><%= image_tag @item.image, size: "280x200" %></td>
        </tr>
        <tr>
          <th>商品名</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格(税抜価格)</th>
          <td><%= (@item.price_without_tax * 1.1).floor %>円
              (<%= @item.price_without_tax %>円)
          </td>
        </tr>
        <tr>
          <th></th>
          <td><%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-success" %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-lg-5">
      <h4>注文詳細画面</h4>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col">
      <p>
        <strong>購入者</strong>
      </p>
    </div>
    <div class="col-lg-11">
      <%= @order.customer.last_name + @order.customer.first_name %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <p>
        <strong>注文日</strong>
      </p>
    </div>
    <div class="col-lg-11">
      <%= @order.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <p>
        <strong>配送先</strong>
      </p>
    </div>
    <div class="col-lg-11">
      <%= @order.postal_code %>
      <%= @order.address %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <p>
        <strong>支払方法</strong>
      </p>
    </div>
    <div class="col-lg-11">
      <%= @order.payment_method_i18n %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-lg-8">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= (order_detail.item.price_without_tax * 1.1).floor %>円</td>
            <td><%= order_detail.amount %>個</td>
            <td><%= (order_detail.subtotal * 1.1).floor %>円</td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-lg-4">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th>商品合計</th>
            <td><%= @order.total_payment %>円</td>
          </tr>
          <tr>
            <th>配送料</th>
            <td><%= @order.shipping_cost %>円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td><%= @order.total_payment + @order.shipping_cost %>円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>